name: Remote Debug
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: actions/setup-java@v3
      with:
       distribution: 'zulu' # Azul Zulu OpenJDK
       java-version: '17'
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.3'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        check-latest: true
    - name: Install Dependencies
      run: |
        sudo cp ./.tmate.conf ~/.tmate.conf
        sudo echo 'PubkeyAcceptedKeyTypes +ssh-rsa' >> /etc/ssh/sshd_config
        sudo service sshd restart
        rm -rf *.js *.md .git .github LICENSE .gitignore
        bash script.sh && exit 0
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: debug-artifact
        path: ${{ github.workspace }}
        retention-days: 3

